In [41]:
# 4. Bonus Question.
# (a) Multiply a 5x3 matrix by a 3x2 matrix (real matrix product) (Hint: create a 5x3 and 3x2 matrices
# and peform matrix multiplication).
# (b) Create a 3x3 identity matrix
# (c) Create a vector with values ranging from 10 to 49).
# (d) Create a null vector of size 10.
# (e) Create a 3x3x3 array with random values

# (f) Create a 5x5 matrix with values 1,2,3,4 just below the diagonal
# (g) Normalize a 5x5 random matrix
# (h) How to get the dates of yesterday, today and tomorrow?
# (i) Find indices of non-zero elements from [1,2,0,0,4,0]. In all the above questions explain your
# approach.

In [ ]:
#My resource of work was google, W3 schools, classwork notebooks and lessons, mathematical computing practical lessons, and the notes files for data science.

a)

In [1]:
#To approach this question,i have started by creating a 5*3 matrix and a 3*2 matrix that
#i am going to assign variables to .
#But before this,first i am going to import libraries to use that is numpy.
#numpy(Numerical Python in full)is a python library that is used to perform mathematical 
#operations on matrices,arrays among others.
#It is also used in machine learning,data analysis among others.
#Datetime and timedelta are python's built-in datetime modules,used for manupulating dates and times.
import numpy as np
from datetime import datetime, timedelta
x=np.array([[2,3,4]  #i have assigned my first matrix(5*3) with a variable 'x'
            ,[5,6,7]
            ,[8,9,1]
            ,[11,12,13]
            ,[14,15,16]])
y=np.array([[1,2]      #then assigned my second matrix(3*2) with a variable 'y'
            ,[3,4]
            ,[5,5]])
#matrix multiplication(dot product) (multiplying the (5*3) matrix 'x' with the (3*2)  matrix 'y'
z=np.dot(x, y)   #My product of matrices 'x' and 'y' is 'z' (i have assigned my product with the variable 'z')
print('The product of matrix x and matix y is:', z)   #Printing the product to get the answer

The product of matrix x and matix y is: [[ 31  36]
 [ 58  69]
 [ 40  57]
 [112 135]
 [139 168]]


In [2]:
#b) Create a 3*3 identity matrix
#An identity matrix refers to the square matrix(with same number of rows and columns) with all  its main
#diagonals as '1' and other elements as '0'.
#To create the identity matrix, i have to assign a variable to my identitymatrix, i have assigned it to 'I' 
#used the command np.eye(),then enter the number of rows and columns i want the identity matrix to have in the 
#brackets which is '3'
I = np.eye(3)
print('The 3*3 identity matrix is:\n',I)

The 3*3 identity matrix is:
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [3]:
#C) Create a vector with values ranging from 10 to 49
#A vector is a list of numbers in jupyter notebook.
vector = np.arange(10,50)  #start is '10' and stop is '50'
print('The vector with values ranging from 10 to 49 is:\n',vector)

The vector with values ranging from 10 to 49 is:
 [10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


In [4]:
#d) Create a null vector with size 10
# A null vector is a list of numbers where all elements are zeros
null_vector = np.zeros(10)
print('The null vector with size 10 is:\n', null_vector)

The null vector with size 10 is:
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [5]:
#e) Create a 3*3*3 array with random values
#A 3x3x3 array with random values is a three-dimensional (3D) numpy array that has 3 layers (along the first 
#axis), each containing a 3x3 matrix with random values between 0 and 1 (unless otherwise specified).
#I am going to use the function np.random.rand() to generate an array with random values.
random_array = np.random.rand(3,3,3)
print('The 3*3*3 random array with random values is:\n',random_array)

The 3*3*3 random array with random values is:
 [[[0.09743971 0.03829608 0.668546  ]
  [0.16544267 0.12725193 0.01909807]
  [0.45766368 0.74761464 0.15506722]]

 [[0.36761741 0.30283188 0.63632497]
  [0.0750478  0.5024375  0.48116921]
  [0.22618221 0.77552289 0.36376974]]

 [[0.81467911 0.8947753  0.55325196]
  [0.99003173 0.66382711 0.50108203]
  [0.22345159 0.38122821 0.94376759]]]


In [6]:
#f) Create a 5x5 matrix with values 1,2,3,4 just below the diagonal
#I am going to use the np.diag() function that is used to create a matrix from a list or an array,
#where the values in the list (or array) are placed along a specified diagonal of a square matrix.
matrix_below_diag = np.diag([1,2,3,4], -1)  #5*5 matrix with values [1,2,3,4] below the diagonal
print('The 5*5 matrix with values 1,2,3,4 just below the diagonal is:\n',matrix_below_diag)

The 5*5 matrix with values 1,2,3,4 just below the diagonal is:
 [[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


In [7]:
#g) Normalize a 5x5 random matrix
#I am going to use the function np.random.random((5, 5)),that creates a 5x5 matrix (array) filled with 
#random floating-point numbers between 0 and 1.
#Normalization involves dividing each element by the maximum value of the matrix, so that the largest value
#becomes 1 and all other values are proportionally scaled.
random_matrix = np.random.random((5,5))
normalized_matrix = random_matrix / np.max(random_matrix)  # normalized 5*5 random matrix
print('The normalized 5*5 random matrix is:\n',normalized_matrix)

The normalized 5*5 random matrix is:
 [[0.21719237 0.8841038  0.87428382 1.         0.40133009]
 [0.11128458 0.9591636  0.47916223 0.0747917  0.13559209]
 [0.23148715 0.23083979 0.25680475 0.55683499 0.30788544]
 [0.10708774 0.36370643 0.18881932 0.99254727 0.2843095 ]
 [0.29167739 0.47599616 0.28001243 0.98438167 0.3134071 ]]


In [8]:
#h) How to get the dates of yesterday, today and tomorrow?
today = datetime.today().date()
yesterday = today - timedelta(days=1)
tomorrow = today + timedelta(days=1)
print('The date of yesterday was:\n', yesterday)  #Yesterday's date
print('The date of today is:\n', today)   #Today's date
print('The date of tomorrow will be:\n', tomorrow)  #Tomorrow's date


The date of yesterday was:
 2024-12-09
The date of today is:
 2024-12-10
The date of tomorrow will be:
 2024-12-11


In [9]:
#(i) Find indices of non-zero elements from [1,2,0,0,4,0]. In all the above questions explain your
#approach.
array = np.array([1,2,0,0,4,0]) #This line creates a NumPy array with the values [1, 2, 0, 0, 4, 0].
                                #The array contains 6 elements, some of which are non-zero (1, 2, 4),
                                #while others are zero (0)
non_zero_indices = np.nonzero(array)[0] #np.nonzero() is a NumPy function that returns the indices of
                                        #the elements in the array that are non-zero.
print('The indices of non-zero elements from [1,2,0,0,4,0] are:\n',non_zero_indices)  #Indices of non-zeroelements in [1,2,0,0,4,0]

The indices of non-zero elements from [1,2,0,0,4,0] are:
 [0 1 4]
